"""Схема UI Global Config: подписи, группы, типы полей.\n\nВынесено из routers/settings.py, чтобы роутер оставался про тонкий HTTP-слой.\n"""

PARAM_LABELS = {
    "static.network.ip_address_mode": "IP Address Mode",
    "static.network.ipv6_enable": "Enable IPv6",
    "static.network.static_dns_enable": "Use Static DNS",
    "static.network.primary_dns": "Primary DNS",
    "static.network.secondary_dns": "Secondary DNS",
    "static.network.vlan.internet_port_enable": "Enable VLAN",
    "static.network.vlan.internet_port_vid": "VLAN ID",
    "static.network.vlan.internet_port_priority": "VLAN Priority (CoS)",
    "ldap.enable": "Enable LDAP",
    "ldap.host": "LDAP Server",
    "ldap.base": "Base DN",
    "ldap.user": "LDAP User",
    "ldap.password": "LDAP Password",
    "ldap.name_attr": "Name Attributes",
    "ldap.numb_attr": "Number Attribute",
    "ldap.name_filter": "Name Filter",
    "ldap.number_filter": "Number Filter",
    "ldap.display_name": "Display Name Format",
    "ldap.call_in_lookup": "Enable Call-In Lookup",
    "ldap.customize_label": "LDAP Label",
    "local_time.time_zone": "Time Zone",
    "local_time.dhcp_time": "Use DHCP Time",
    "local_time.summer_time": "Enable Summer Time",
    "local_time.date_format": "Date Format",
    "local_time.time_zone_name": "Time Zone Name",
    "static.auto_provision.server.url": "Provisioning Server URL",
    "static.auto_provision.power_on": "Auto Provision on Power On",
    "static.auto_provision.repeat.minutes": "Repeat Interval (minutes)",
    "static.auto_provision.custom.protect": "Protect Custom Settings",
    "static.auto_provision.weekly.enable": "Enable Weekly Provisioning",
    "static.auto_provision.username": "Provisioning Username",
    "static.auto_provision.password": "Provisioning Password",
    "features.action_uri_limit_ip": "Action URI Allowed Server IP",
    "features.action_uri.phone.enable": "Enable Phone Action URI",
    "features.action_uri.expansion_module.enable": "Enable Expansion Module Action URI",
    "action_url.enable": "Enable Action URL",
    "action_url.limit_ip": "Action URL Limit IP",
    "action_url.registered": "Registered URL",
    "action_url.unregistered": "Unregistered URL",
    "action_url.register_failed": "Registration Failed URL",
    "action_url.registration_failed": "Registration Failed URL (legacy)",
    "action_url.off_hook": "Off Hook URL",
    "action_url.on_hook": "On Hook URL",
    "action_url.incoming_call": "Incoming Call URL",
    "action_url.outgoing_call": "Outgoing Call URL",
    "action_url.call_established": "Call Established URL",
    "action_url.call_missed": "Call Missed URL",
    "action_url.dnd_on": "DND On URL",
    "action_url.dnd_off": "DND Off URL",
    "action_url.setup_completed": "Setup Completed URL",
    "action_url.setup_complete": "Setup Complete URL (legacy)",
    "features.remote_phonebook.enable": "Enable Remote Phonebook",
    "features.dnd.allow": "Allow DND",
    "features.fwd.allow": "Allow Forward",
    "features.show_action_uri_option": "Show Action URI Option",
    "phone_setting.ring_type": "Ring Tone",
    "voice.handset.spk_vol": "Handset Speaker Volume",
    "voice.ring_vol": "Ring Volume",
    "directory.edit_default_input_method": "Directory Input Method",
    "action_url.show_msgbox": "Show Action URL Message Box",
    "ncdc.phone.admin_password": "Phone admin password",
    "ncdc.phone.user_password": "Phone user password",
}

SELECT_OPTIONS = {
    "static.network.ip_address_mode": {
        "0": "IPv4 Only",
        "1": "IPv6 Only",
        "2": "IPv4 & IPv6",
    },
    "local_time.date_format": {
        "0": "WWW MMM DD",
        "1": "DD-MMM-YY",
        "2": "YYYY-MM-DD",
        "3": "DD/MM/YYYY",
        "4": "MM/DD/YY",
        "5": "DD MMM YYYY",
    },
    "local_time.time_zone": {
        "-12": "UTC-12",
        "-11": "UTC-11",
        "-10": "UTC-10",
        "-9": "UTC-9",
        "-8": "UTC-8 (PST)",
        "-7": "UTC-7 (MST)",
        "-6": "UTC-6 (CST)",
        "-5": "UTC-5 (EST)",
        "-4": "UTC-4",
        "-3": "UTC-3",
        "-2": "UTC-2",
        "-1": "UTC-1",
        "0": "UTC+0 (GMT)",
        "+1": "UTC+1 (CET)",
        "+2": "UTC+2 (EET)",
        "+3": "UTC+3 (MSK)",
        "+4": "UTC+4",
        "+5": "UTC+5",
        "+6": "UTC+6",
        "+7": "UTC+7",
        "+8": "UTC+8",
        "+9": "UTC+9",
        "+10": "UTC+10 (VLAT)",
        "+11": "UTC+11",
        "+12": "UTC+12",
    },
}

PARAM_GROUPS = {
    "Network": [
        "static.network.ip_address_mode",
        "static.network.ipv6_enable",
        "static.network.static_dns_enable",
        "static.network.primary_dns",
        "static.network.secondary_dns",
        "static.network.vlan.internet_port_enable",
        "static.network.vlan.internet_port_vid",
        "static.network.vlan.internet_port_priority",
    ],
    "LDAP": [
        "ldap.enable",
        "ldap.host",
        "ldap.base",
        "ldap.user",
        "ldap.password",
        "ldap.name_attr",
        "ldap.numb_attr",
        "ldap.name_filter",
        "ldap.number_filter",
        "ldap.display_name",
        "ldap.call_in_lookup",
        "ldap.customize_label",
    ],
    "Time & Date": [
        "local_time.time_zone",
        "local_time.dhcp_time",
        "local_time.summer_time",
        "local_time.date_format",
        "local_time.time_zone_name",
    ],
    "Auto Provision": [
        "static.auto_provision.server.url",
        "static.auto_provision.username",
        "static.auto_provision.password",
        "static.auto_provision.power_on",
        "static.auto_provision.repeat.minutes",
        "static.auto_provision.custom.protect",
        "static.auto_provision.weekly.enable",
    ],
    "Phone Web UI": [
        "ncdc.phone.admin_password",
        "ncdc.phone.user_password",
    ],
    "Action URI": [
        "features.action_uri_limit_ip",
        "features.action_uri.phone.enable",
        "features.action_uri.expansion_module.enable",
    ],
    "Action URL Events": [
        "action_url.enable",
        "action_url.limit_ip",
        "action_url.registered",
        "action_url.unregistered",
        "action_url.register_failed",
        "action_url.off_hook",
        "action_url.on_hook",
        "action_url.incoming_call",
        "action_url.outgoing_call",
        "action_url.call_established",
        "action_url.call_missed",
        "action_url.dnd_on",
        "action_url.dnd_off",
        "action_url.setup_completed",
    ],
    "Features": [
        "features.remote_phonebook.enable",
        "features.dnd.allow",
        "features.fwd.allow",
        "features.show_action_uri_option",
        "phone_setting.ring_type",
        "voice.handset.spk_vol",
        "voice.ring_vol",
        "directory.edit_default_input_method",
        "action_url.show_msgbox",
    ],
}

BOOLEAN_PARAMS = {
    "static.network.ipv6_enable",
    "static.network.static_dns_enable",
    "static.network.vlan.internet_port_enable",
    "ldap.enable",
    "ldap.call_in_lookup",
    "local_time.dhcp_time",
    "local_time.summer_time",
    "static.auto_provision.power_on",
    "static.auto_provision.custom.protect",
    "static.auto_provision.weekly.enable",
    "features.action_uri.phone.enable",
    "features.action_uri.expansion_module.enable",
    "features.remote_phonebook.enable",
    "features.dnd.allow",
    "features.fwd.allow",
    "features.show_action_uri_option",
    "action_url.show_msgbox",
    "action_url.enable",
}

INT_PARAMS = {
    "static.network.vlan.internet_port_vid",
    "static.network.vlan.internet_port_priority",
    "static.auto_provision.repeat.minutes",
    "voice.handset.spk_vol",
    "voice.ring_vol",
}

PASSWORD_PARAMS = {
    "ldap.password",
    "static.auto_provision.password",
    "ncdc.phone.admin_password",
    "ncdc.phone.user_password",
}
